### ISSUE TITLE
CarePlan.participant.member

### ISSUE THREAD

**Issue by brettmarquard** [argonautproject/data-query#24]
In the [CareTeam Profile](http://build.fhir.org/ig/Healthedata1/Argo-DSTU2/StructureDefinition-argo-careteam.html), did we mean to restrict to the Argonaut-patient profile?

I think we meant to allow practitioner and relatedPerson

**Comment by Healthedata1** [comment]
good catch and fixed.

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com <ehaas@healhtedatainc.com>

**Comment by Healthedata1** [comment]
also updated US-Core
