### ISSUE TITLE
GG punch list for publishing

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/data-query#32]
1.  fix the CVX codes - doesn't expand in CVX -not an IG issue
2.  can you change the list fragment style for extensions, valeusets etc to just list the artifact and not the definitions? - for examples see http://www.fhir.org/guides/argonaut/r2/valuesets.html 
3.  have someone else be able to publish to fhir.org 
4.  check the qa errors
     -  It think they are all narrative generation issues
     -  on the broken link - renders fine minor issue 
5.  Update the index.html page blurb in the yellow box to reflect its published status
6.  publish final after Brett reviews the Git version

**Comment by grahamegrieve** [comment]
>
>
>    1. can you change the list fragment style for extensions, valeusets
>    etc to just list the artifact and not the definitions? - for examples see
>    http://www.fhir.org/guides/argonaut/r2/valuesets.html
>    <http://www.fhir.org/guides/argonaut/r2/valuesets.html>
>
>
use list-simple-valuesets instead of list-valuesets for the $include

Grahame
