### ISSUE TITLE
Clarify the intent of the argonaut category in vitals

### ISSUE THREAD

**Issue by torresdrew** [argonautproject/data-query#46]
I have been asked about using the Argonaut category value set for the vitals profile. I was under the impression the category is intended to tag vitals in a standard way. Others are interpreting it such that when you query with the Argonaut vital category, you will only get vitals that have a code value from the LOINC vital table from the IG.

Is the guidance for those trying to only get observations that contain a LOINC code to use the category search, or use the LOINC codes from the table to query? I think if you only want observations with a a LOINC code from the table you should query by the LOINC codes, and the category search can include other vitals.

**Comment by brettmarquard** [comment]
Thanks Drew.

Current text under category search:

"Search based on vital sign category code. This search fetches a bundle of all Observation resources with category ‘vital-signs’ for the specified patient (how to search by reference) and (how to search by token). The table **above is the minimum set, additional vital signs are allowed.**"

How should we make this more clear?

**Comment by torresdrew** [comment]
Consider this resolved then. I couldn't find that text. I knew that was the intent, but in discussions with others, they felt it wasn't clear.

I found the text now.
